"""Commodity name resolution for EDTradeAssist.

One commodity has up to four spellings in play at once:

    journal   $gold_name;      FDev symbol  Gold
    display   Gold             Ardent       gold

The bundled edta_commodities.json (generated by tools/build_commodities.py from
EDCD/FDevIDs) is the bijection between them. Everything normalises onto one key -
casefolded, punctuation and spaces stripped - so 'CMM Composite', 'cmmcomposite'
and '$cmmcomposite_name;' all land on the same record.

An unresolved name is an error carrying suggestions, never a silent best guess:
hauling to the wrong commodity wastes a whole round trip.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional

_JOURNAL_SYMBOL = re.compile(r"^\$(?P<symbol>.+?)_name;$", re.IGNORECASE)
_NON_ALNUM = re.compile(r"[^a-z0-9]")

_TABLE_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "edta_commodities.json")


def lookup_key(value: str) -> str:
    """Normalise any spelling onto the single lookup key."""
    text = (value or "").strip()
    match = _JOURNAL_SYMBOL.match(text)
    if match:
        text = match.group("symbol")
    return _NON_ALNUM.sub("", text.casefold())


def same_commodity(a: str, b: str) -> bool:
    """Whether two spellings name the same commodity.

    Market.json and the journal write '$gold_name;', Ardent writes 'gold', the
    panel writes 'Gold'. The empty check is not redundant: without it two
    unresolvable names both normalise to '' and would compare equal.
    """
    key = lookup_key(a)
    return bool(key) and key == lookup_key(b)


def edit_distance(a: str, b: str, limit: int) -> int:
    """Levenshtein distance, giving up once it exceeds `limit`.

    Written out rather than imported from difflib: EDMC ships a FROZEN Python
    whose library.zip carries only the stdlib modules EDMC itself uses, and
    difflib is not among them. A plugin importing it fails to load outright.
    See tests/test_core.py::FrozenRuntimeImports.
    """
    if abs(len(a) - len(b)) > limit:
        return limit + 1
    if not a:
        return len(b)
    if not b:
        return len(a)

    previous = list(range(len(b) + 1))
    for i, char_a in enumerate(a, start=1):
        current = [i]
        best = i
        for j, char_b in enumerate(b, start=1):
            cost = 0 if char_a == char_b else 1
            value = min(previous[j] + 1,          # deletion
                        current[j - 1] + 1,       # insertion
                        previous[j - 1] + cost)   # substitution
            current.append(value)
            if value < best:
                best = value
        if best > limit:
            return limit + 1
        previous = current
    return previous[-1]


def _suggestion_limit(key: str) -> int:
    """How wrong a spelling may be and still earn a suggestion. Scales with
    length so short names do not match half the table."""
    return max(1, min(3, len(key) // 3 + 1))


@dataclass(frozen=True)
class Commodity:
    symbol: str
    name: str
    category: str
    ardent: str
    rare: bool = False


@dataclass
class Resolution:
    """The outcome of resolving typed text. `ok` is the only thing to branch on."""

    ok: bool
    commodity: Optional[Commodity] = None
    suggestions: List[str] = field(default_factory=list)
    error: str = ""


class CommodityTable:
    def __init__(self, records: List[Commodity]):
        self.records = records
        self._by_key: Dict[str, Commodity] = {}
        for record in records:
            for spelling in (record.name, record.symbol, record.ardent):
                key = lookup_key(spelling)
                if key:
                    self._by_key.setdefault(key, record)

    def __len__(self) -> int:
        return len(self.records)

    def names(self) -> List[str]:
        return [record.name for record in self.records]

    def resolve(self, text: str) -> Resolution:
        raw = (text or "").strip()
        if not raw:
            return Resolution(False, error="No commodity entered.")
        key = lookup_key(raw)
        record = self._by_key.get(key)
        if record is not None:
            return Resolution(True, commodity=record)
        return Resolution(False, suggestions=self.suggest(key),
                          error="Unknown commodity: {!r}".format(raw))

    def suggest(self, key: str, count: int = 5) -> List[str]:
        """Display names closest to a key that did not resolve."""
        limit = _suggestion_limit(key)
        scored = []
        for candidate, record in self._by_key.items():
            distance = edit_distance(key, candidate, limit)
            if distance <= limit:
                scored.append((distance, abs(len(candidate) - len(key)), record.name))
        scored.sort()
        seen: List[str] = []
        for _, _, name in scored:
            if name not in seen:
                seen.append(name)
            if len(seen) >= count:
                break
        return seen


_table: Optional[CommodityTable] = None


def table(path: str = _TABLE_PATH) -> CommodityTable:
    """The bundled table, loaded once."""
    global _table
    if _table is None:
        with open(path, "r", encoding="utf-8") as handle:
            data = json.load(handle)
        _table = CommodityTable([
            Commodity(symbol=row["symbol"], name=row["name"],
                      category=row.get("category", ""), ardent=row["ardent"],
                      rare=bool(row.get("rare")))
            for row in data.get("commodities", [])
        ])
    return _table


def resolve(text: str) -> Resolution:
    return table().resolve(text)


def _self_test() -> None:
    tbl = table()
    assert len(tbl) > 200, len(tbl)

    for spelling in ("Gold", "gold", "  GOLD ", "$gold_name;"):
        got = tbl.resolve(spelling)
        assert got.ok and got.commodity.ardent == "gold", spelling

    multi = tbl.resolve("consumer technology")
    assert multi.ok and multi.commodity.ardent == "consumertechnology", multi

    for typo, expected in (("Palladum", "Palladium"), ("Platnum", "Platinum"),
                           ("Golde", "Gold"), ("Galde", "Gold"),
                           ("Bertrandit", "Bertrandite"),
                           ("Consumer Tecnology", "Consumer Technology")):
        miss = tbl.resolve(typo)
        assert not miss.ok, typo
        assert expected in miss.suggestions, (typo, miss.suggestions)

    assert not tbl.resolve("").ok
    assert tbl.resolve("zzzzzzzzzzzz").suggestions == []

    assert edit_distance("gold", "gold", 3) == 0
    assert edit_distance("golde", "gold", 3) == 1
    assert edit_distance("galde", "gold", 3) == 2
    assert edit_distance("abcdefgh", "zz", 2) == 3        # bailed out at the limit

    assert lookup_key("CMM Composite") == lookup_key("$cmmcomposite_name;")

    assert same_commodity("$gold_name;", "gold")
    assert same_commodity("Gold", "gold") and same_commodity("CMM Composite", "cmmcomposite")
    assert not same_commodity("gold", "silver")
    assert not same_commodity("", "") and not same_commodity("gold", "")

    print("edta_commodities self-test: OK ({} commodities)".format(len(tbl)))


if __name__ == "__main__":
    _self_test()
